baseURL = "https://0x69.ru/"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true
title = "0x69.ru"
theme = "dream"

[languages]
  [languages.ru]
    languageName = "Русский"
    languageCode = "ru"
    contentDir = "content/russian"
    weight = 1
  [languages.en]
    languageName = "English"
    languageCode = "en"
    contentDir = "content/english"
    weight = 2

[services]
  [services.googleAnalytics]
    ID = "G-EGGNL85KC3"

[params]
yandexMetricaId = "99568144"
lightTheme = "emerald"
darkTheme = "dim"
author = "Rianvy"
description = "В этом личном блоге я делюсь заметками о технологиях, жизни и обо всём, что меня вдохновляет."
avatar = "img/avatar.jpg"
motto = "Document today what you will forget tomorrow"
headerTitle = "0x69.ru </>"
footerBottomText = "Powered by ❤️"
rss = true
# utterancesRepo = ""
# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# waline = true
# walineServer = ""
#comments.app
commentsApp = false
commentsAppSiteID = "YjlEv4KV"
commentsAppLimit = "10"
#Telegram Comments
#telegramComments = true
#telegramCommentsHomeId = ""
email = "blackghost.v1@gmail.com"
siteStartYear = 2025
# Syntax highlighting
#https://github.com/highlightjs/highlight.js/tree/main/src/languages
SyntaxHighlighting = true
SyntaxHighlightingThemeLight = "atom-one-light"
SyntaxHighlightingThemeDark = "github-dark-dimmed"
SyntaxHighlightingLanguages = ["apache", "json", "javascript", "typescript", "bash", "shell", "sh", "zsh", "powershell", "ini", "nginx", "php"]
# options
stickyNav = true
portfolio = true
utilities = true
reorderNavItems = ["search", "categories", "portfolio", "posts", "utilities", "tags", "github", "rss",]
collapseNavItems = ["posts", "tags", "github", "rss"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp", "share"]
backToTop = false

[params.advanced]
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]

[markup]
  [markup.highlight]
    codeFences = false
    guessSyntax = false

[params.navItems]
github = { href = "https://github.com/rianvy", target = "_blank", icon = "logo-github", title = "GitHub" }

[params.navLang]
ru = { href = "/ru/", icon = "language", title = "Русский" }
en = { href = "/en/", icon = "language", title = "English" }

[params.experimental]
jsDate = true
jsDateFormat = "dd.MM.yyyy, HH:mm"

[params.giscus]
enable = true
repo = "Rianvy/blog"
repoId = "R_kgDONpZnjw"
category = "Comments"
categoryId = "DIC_kwDONpZnj84C2KjB"
mapping = "pathname"
strict = true
reactionsEnabled = true
inputPosition = "top"
lang = "ru"
loading = "lazy"